{
	"version": 1543428887,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bg1-sheet0.png",
		"images/point1-sheet0.png",
		"images/player1-sheet0.png",
		"images/player1-sheet1.png",
		"images/ground1-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/bg2-sheet0.png",
		"images/door-sheet0.png",
		"images/point2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/bg3-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/money-sheet0.png",
		"images/point3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/bg4-sheet0.png",
		"images/box1-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/bghome-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/bglond-sheet0.png",
		"images/bglonding-sheet0.png",
		"images/londer.png",
		"images/winer-sheet0.png",
		"images/backhome-sheet0.png",
		"media/ต่อย.ogg",
		"media/ตี๋.ogg",
		"media/ปริ๊ง2.ogg",
		"media/เก็บ.ogg",
		"media/เอ่อ (online-audio-converter.com).ogg",
		"media/yahu (online-audio-converter.com).ogg",
		"media/ลง 3 (online-audio-converter.com).ogg",
		"media/sound effects เสียงปรบมือ (online-audio-converter.com).ogg",
		"media/videoplay (online-audio-converter.com).ogg"
	]
}